### ISSUE TITLE
Can no longer install on HASSOS

### ISSUE THREAD

**Issue by R5fan** [kevinvincent/hassio-addons#22]
Installing the addon throws this error on HAOS running 2021.8.8
```
tarting build for 8c1e12d6/amd64-addon-sonos_audioclip_tts:2.0.3
21-08-24 16:35:14 ERROR (SyncWorker_2) [supervisor.docker.addon] Can't build 8c1e12d6/amd64-addon-sonos_audioclip_tts:2.0.3: The command '/bin/ash -o pipefail -c apk add --no-cache nodejs nodejs-npm' returned a non-zero code: 1
21-08-24 16:35:14 ERROR (SyncWorker_2) [supervisor.docker.addon] Build log: 
Step 1/15 : ARG BUILD_FROM
Step 2/15 : FROM $BUILD_FROM
 ---> 8fc812b16962
Step 3/15 : ENV LANG C.UTF-8
 ---> Using cache
 ---> fa67bf397352
Step 4/15 : RUN apk add --no-cache nodejs nodejs-npm
 ---> Running in 10cdd8ba3624
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:

  nodejs-npm (no such package):
    required by: world[nodejs-npm]
Removing intermediate container 10cdd8ba3624
```
I have used this addon extensively on my old HA server, but now Im redoing my configuration from scratch and I seem to be missing something? Help, i need this addon :)

edit: i made a snapshot of just this addon on my old install and restored that on my new one, and that seems to work. Its a good workaround for me, but not for others..

**Comment by BergCyrill** [comment]
I have noticed the same behaviour and already created a PR for merge.
The way you have to install nodejs with npm has changed since alpine 3.8

#23

**Comment by evilone68** [comment]
error i get installing from repository option in home assistant in docker " The command '/bin/ash -o pipefail -c apk add --no-cache nodejs nodejs-npm' returned a non-zero code: 1 "

any updates if there is a workaround?

**Comment by BergCyrill** [comment]
I have already provided the solution.
As long as the PR isn’t merged you could add my repository (which is just a fork with the fix) to HA:

https://github.com/BergCyrill/hassio-addons

**Comment by brianhatchet** [comment]
@kevinvincent you should really merge in @BergCyrill 's MR. The integration in HASS is currently broken due to the name change

**Comment by kevinvincent** [comment]
Merged. Sorry!
