### ISSUE TITLE
Stopped running in Hassio

### ISSUE THREAD

**Issue by connoleg** [kevinvincent/hassio-addons#4]
Hi
when starting the plugin I get the following in the log:

> s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> ifelse: fatal: unable to exec ./run.sh: Exec format error
> [cmd] ./run.sh exited 126
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.

Any ideas whats going on please?
Thanks

**Comment by kevinvincent** [comment]
Can you reinstall and let me know if the update fixes it? I don't have it running right now to test.

**Comment by kevinvincent** [comment]
Confirmed that update fixes it.
