### ISSUE TITLE
Correct Syntax for MP3 clip

### ISSUE THREAD

**Issue by mayhew132** [kevinvincent/hassio-addons#7]
Please could someone advise what is the correct syntax to use when using an MP3 clip rather than TTS, at the moment I have an MP3 called “test.mp3” which I’m trying to call using the following URL:

http://hassio.local:8349/api/playClip?playerId=<playerID>&streamUrl=http://servername/test.mp3&volume=30

It doesn’t pull the test.mp3 from the web server and errors.

Any help would be appreciated?

**Comment by OverZealous** [comment]
Are you encoding the streamUrl? Since it's a URL inside a URL, you should encode the url, which would look something like `http%3A%2F%2Fservername%2Ftest.mp3` making the full URL:

```
http://hassio.local:8349/api/playClip?playerId=abc_123&streamUrl=http%3A%2F%2Fservername%2Ftest.mp3&volume=30
```

Don't forget you need the player ID, too.

**Comment by mayhew132** [comment]
Hi there, 

Thanks for the tip, I’ve gone an encoded the url (in my case http://192.168.3.8/Alert.mp3 however it seems to still be erroring when I submit.

This is the URL being accessed:

http://192.168.3.8:8349/api/playClip?playerId=RINCON_xxxxxxxxxxxxxxxx&streamURL=http%3A%2F%2F192.168.3.8%2FAlert.mp3&volume=50

The response I get is:
{"success":false,"error":"Missing Parameters"}

I can’t seem to see what might be wrong, the audio file loads fine when I access with just the URL.

Cheers
Guy

**Comment by OverZealous** [comment]
In your example, the case is wrong for the `streamUrl`. The `r` and `l` shouldn’t be capitalized.

**Comment by mayhew132** [comment]
Bingo! Thank you very much :)
